#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with $1$ and $2$, the first $10$ terms will be:
#$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89,$$
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.


# Entrada
print('Sequência de Fibonacci:')
print('-' * 30)
print('Qual é o limite?')

# Variável int para o usuário definir o limite
limite = int(input())

# Sequência de Fibonacci até o valor limite e soma dos números pares
a, b = 1, 2
soma_pares = 0
while a <= limite:
    if a % 2 == 0:
        soma_pares += a
    print(a)
    a, b = b, a + b
   # print()

print('-' * 30)
print(f'A soma dos números pares da sequência de Fibonacci até {limite} é: {soma_pares}')